apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-web
  name: demo-web
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - image: nginx
    name: website-from-repo
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  initContainers:
  - image: alpine/git:1.0.17
    name: git-clone
    command: ['/bin/sh', '-c']        
    args: ['git clone https://github.com/javajon/dijure.com && mv public/* html/']
    volumeMounts:
    - name: html
      mountPath: /html/
