apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-web
  name: demo-web
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - image: nginx
    name: website-from-repo
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  initContainers:
  - image: alpine/git
    name: git-clone
    args:
    - /bin/sh
    - -c
    - >
      git clone https://github.com/javajon/dijure.com
      cp public/ html/
    volumeMounts:
    - name: html
      mountPath: /html/
