apiVersion: v1
kind: Pod
metadata:
  name: world-population
spec:
  containers:
    - name: world-population-app
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 5 && cat /etc/config/api.txt; done;" ]
      volumeMounts:
      - name: api-sources
        mountPath: /etc/config
  volumes:
    - name: api-sources
      configMap:
        name: population
        items:
        - key: worldpop.api
          path: api.txt
