apiVersion: v1
kind: Pod
metadata:
  name: world-population
spec:
  containers:
    - name: world-population-app
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","cat /etc/config/api" ]
      volumeMounts:
      - name: api-sources
        mountPath: /etc/config
  volumes:
    - name: api-sources
      configMap:
        name: population
        items:
        - key: worldpop.api
          path: api.txt
