apiVersion: v1
kind: Service
metadata:
  name: mountains
spec:
  ports:
  - name: client
    nodePort: 30300
    port: 3000
    targetPort: client 
  selector:
    app: mountains
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mountains
  labels:
    app: mountains
spec:
  selector:
    matchLabels:
      app: mountains
  replicas: 1
  template:
    metadata:
      labels:
        app: mountains
    spec:
      containers:
      - name: mountains-client
        image: $REGISTRY/mountains-client-secure:$APP_VERSION
        imagePullPolicy: Always
        ports:
          - name: client
            containerPort: 3000
        env:
          - name: DEBUG
            value: "express:*"
          - name: GRPC_VERBOSITY
            value: "DEBUG"
          - name: GRPC_TRACE
            value: "all"
          - name: MOUNTAINS_SERVER
            value: "localhost:8321"
      - name: mountains-server
        image: $REGISTRY/mountains-server-secure:$APP_VERSION
        imagePullPolicy: Always
        ports:
          - name: grpc
            containerPort: 8321
        env:
          - name: DEBUG
            value: "express:*"
          - name: GRPC_VERBOSITY
            value: "DEBUG"
          - name: GRPC_TRACE
            value: "all"
