apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  ports:
  - name: web
    nodePort: 30300
    port: 3000
    targetPort: web 
  selector:
    app: $APP_NAME
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $REGISTRY/$APP_NAME:$APP_VERSION
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
        env:
          - name: DEBUG
            value: "express:*"
          - name: GRPC_VERBOSITY
            value: "DEBUG"
          - name: GRPC_TRACE
            value: "all"
          - name: MOUNTAINS_SERVER
            value: "mountains-server-secure:8321"
