apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  ports:
  - name: grpc
    port: 8321
    protocol: TCP
    targetPort: grpc
  selector:
    app: $APP_NAME
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $REGISTRY/$APP_NAME:$APP_VERSION
        imagePullPolicy: Always
        ports:
          - name: grpc
            containerPort: 8321
        env:
          - name: DEBUG
            value: "express:*"
          - name: GRPC_VERBOSITY
            value: "DEBUG"
          - name: GRPC_TRACE
            value: "all"
